# Generated by Django 2.1.7 on 2019-05-21 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('company', models.BooleanField(default='False')),
                ('opleidingen', models.TextField(default='None')),
                ('regio', models.TextField(default='None')),
                ('werkervaring', models.TextField(default='None')),
                ('telefoon', phonenumber_field.modelfields.PhoneNumberField(default='None', max_length=128)),
                ('talen', models.TextField(default='None')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
